import os
import glob
import argparse
import shutil
import subprocess

def undistort_all_frames(dataset_root, colmap_executable="colmap"):
    """
    Apply Frame 0 calibration (distorted/sparse) to ALL frames' masked images.
    """
    # Frame 0 paths
    frame0_path = os.path.join(dataset_root, "0")
    sparse_path = os.path.join(frame0_path, "distorted", "sparse", "0")
    
    if not os.path.exists(sparse_path):
        print(f"Error: Calibration not found at {sparse_path}")
        return

    # Find all frame directories
    # Assuming standard structure: dataset_root/FRAME_ID
    frame_dirs = sorted([d for d in os.listdir(dataset_root) if os.path.isdir(os.path.join(dataset_root, d))])
    
    print(f"Found {len(frame_dirs)} frames. Applying calibration...")

    for frame_id in frame_dirs:
        frame_dir = os.path.join(dataset_root, frame_id)
        
        # We need to undistort the MASKED images (in 'images' folder generated by auto_process)
        # auto_process.py outputted to: frame_dir/images/VIEW_ID.png
        # Rename 'images' to 'input' for colmap
        
        input_dir = os.path.join(frame_dir, "input")
        images_dir = os.path.join(frame_dir, "images")
        
        # If 'images' exists and 'input' doesn't, rename it
        if os.path.exists(images_dir) and not os.path.exists(input_dir):
            shutil.move(images_dir, input_dir)
        elif not os.path.exists(input_dir):
            if frame_id == "0":
                # Frame 0 is special, input_masked was already created manually
                # Let's ensure 'input' points to masked images for undistortion
                if os.path.exists(os.path.join(frame_dir, "input_masked")):
                     # Use input_masked as source
                     # Actually, for Frame 0, convert.py already ran on 'input' (raw).
                     # We want to re-run undistortion on 'input_masked'.
                     pass
            else:
                print(f"Skipping {frame_id}: No input images found")
                continue

        # Prepare paths
        # Source uses 'input_masked' if available (for Frame 0), else 'input'
        if frame_id == "0":
            image_src = os.path.join(frame_dir, "input_masked")
            if not os.path.exists(image_src):
                print("Warning: Frame 0 masked images missing?")
                continue
        else:
            image_src = input_dir

        output_path = frame_dir # Colmap outputs 'images' and 'sparse' here
        
        # Create output dir if not exist
        os.makedirs(output_path, exist_ok=True)
        
        print(f"Undistorting Frame {frame_id}...")
        
        cmd = [
            colmap_executable, "image_undistorter",
            "--image_path", image_src,
            "--input_path", sparse_path,
            "--output_path", output_path,
            "--output_type", "COLMAP"
        ]
        
        # Run
        # We need offscreen platform if headless
        env = os.environ.copy()
        env["QT_QPA_PLATFORM"] = "offscreen"
        
        subprocess.run(cmd, env=env, check=True)
        
    print("All frames undistorted.")

if __name__ == "__main__":
    parser = argparse.ArgumentParser()
    parser.add_argument("--dataset_root", required=True)
    args = parser.parse_args()
    
    undistort_all_frames(args.dataset_root)
